exp_name: simplesr test

output_dir: D:\codes\SimpleSR\output
scale: 4
manual_seed: ~

model_type: SwinIRModel
model:
  name: ${model_type}
  path: simplesr.models.base_sr_model.SRModel

datasets:
  train:
    path: simplesr.data.dataset.PairedImageDataset
    kwargs:
      name: test_DOTA
      dataroot_gt: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\train\images
      dataroot_lq: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\train_lrx4\images
      phase: train
      use_augment: false
      scale: ${scale}
      io_backend_opt:
        type: disk
    # data loader
    # sampler
    dataset_enlarge_ratio: 100
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    prefetch_mode: cpu
    num_prefetch_queue: 2
    pin_memory: true
    persistent_workers: true

  val:
    path: simplesr.data.dataset.PairedImageDataset
    kwargs:
      name: test_DOTA_val
      dataroot_gt: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\val\images
      dataroot_lq: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\val_lrx4\images
      phase: val
      use_augment: false
      scale: 4
      io_backend_opt:
        type: disk

    batch_size: 32
    num_worker: 8

# network structures
network_g:
  name: SwinIR
  path: simplesr.networks.SwinIR.SwinIR
  kwargs:
    upscale: 4
    in_chans: 3
    img_size: 64
    window_size: 8
    img_range: 1.
    depths: [6, 6, 6, 6]
    embed_dim: 128
    num_heads: [4, 4, 4, 4]
    mlp_ratio: 2
    upsampler: 'pixelshuffle'
    resi_connection: '1conv'


train:
  ema_decay: 0.999

  total_iter: 1e5
  warmup_iter: -1  # no warm up

  # losses 像素损失和感知损失
  pixel_opt:
    path: simplesr.losses.basic_loss.L1Loss
    kwargs:
      loss_weight: 1.0
      reduction: mean
  # 优化器
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  # 学习率调度器
  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher
    ssim:
      type: SSIM
      crop_border: 4
      better: higher

# logging settings
log_settings:
  print_freq: 100
  save_checkpoint_freq: 5000
  train_pbar: true

  wandb:
    project: run_exp
    resume_id: ~
    mode: online
