exp_name: simplesr test

output_dir: D:\codes\SimpleSR\output
scale: 4

model_type: SwinIRModel
model:
  name: ${model_type}
  path:
  kwargs:

datasets:
  train:
    name: test_DOTA
    path: simplesr.data.dataset.PairedImageDataset
    kwargs:
      dataroot_gt: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\train\images
      dataroot_lq: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\train_lrx4\images
      phase: train
      use_augment: false
      scale: ${scale}
      io_backend_opt:
        type: disk
    # data loader
    # sampler
    dataset_enlarge_ratio: 1
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    prefetch_mode: cpu
    num_prefetch_queue: 1

  val:
    name: test_DOTA_val
    path: simplesr.data.dataset.PairedImageDataset
    kwargs:
      dataroot_gt: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\val\images
      dataroot_lq: D:\codes\SimpleSR\dataset\DOTA_crop_dataset\dota_samples\val_lrx4\images
      phase: val
      use_augment: false
      scale: 4
      io_backend_opt:
        type: disk

    batch_size: 32
    num_worker: 8

# network structures
network_g:
  name: SwinIR
  path: simplesr.networks.SwinIR.SwinIR
  kwargs:
    upscale: 4
    in_chans: 3
    img_size: 64
    window_size: 8
    img_range: 1.
    depths: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    upsampler: 'pixelshuffle'
    resi_connection: '1conv'


train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

  total_iter: 1e6
  warmup_iter: -1  # no warm up

  save_checkpoint_freq: !!float 5e3

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: SSIM
      crop_border: 4

# logging settings
log_settings:
  print_freq: 100

  wandb:
    project: run_exp
    resume_id: ~
